name: Build Jekyll with Scholar
on: [push, pull_request]  # Trigger on both events
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Match Jekyll 4.x requirement
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install jekyll -v 4.3.3
          gem install jekyll-scholar -v 7.0
          bundle install

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --trace --future
          
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Explicitly upload the built site  
        
      - name: Deploy
        uses: actions/deploy-pages@v4