name: Build Jekyll with Scholar
on: [push, pull_request]  # Trigger on both events
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:  # ← THIS IS CRUCIAL
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    permissions:
      contents: write
      pages: write
      id-token: write  # This is the critical permission
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Match Jekyll 4.x requirement
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install jekyll -v 4.3.3
          gem install jekyll-scholar -v 7.0
          bundle install

      - name: Build with Jekyll
#        env:
#          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --trace
#          ls -la _site/  # Verify files are generated
          
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site' # Explicitly upload the built site  
        
      - name: Deploy to GitHub Pages
        id: deployment  # ← NOTE THIS ID
        uses: actions/deploy-pages@v4